- BUILD.bazel
- README.md
- WORKSPACE
- bazel_integration_test/BUILD.bazel
- bazel_integration_test/deps.bzl
- bazel_integration_test/internal/BUILD.bazel
- bazel_integration_test/internal/bazel_integration_test.bzl
- bazel_integration_test/internal/default_test_runner.bzl
- bazel_integration_test/internal/default_test_runner.sh
- bazel_integration_test/internal/integration_test_wrapper.sh
- doc/BUILD.bazel
- examples/BUILD.bazel
- examples/custom_test_runner/WORKSPACE
- examples/simple/BUILD.bazel
- examples/simple/WORKSPACE
- examples/simple/mockascript/BUILD.bazel
- examples/simple/mockascript/internal/BUILD.bazel
- examples/simple/tests/BUILD.bazel
- examples/use_create_scratch_dir_test.sh
- tests/BUILD.bazel
- tests/tools_tests/BUILD.bazel
- tests/tools_tests/create_scratch_dir_test.sh
- tests/tools_tests/find_child_workspace_packages_test.sh
- tests/tools_tests/update_deleted_packages_test.sh
- tools/BUILD.bazel
- tools/create_scratch_dir.sh
- tools/find_child_workspace_packages.sh
- tools/update_deleted_packages.sh
Related to cgrindel/bazel-starlib#44.
> Migrate from `rules_bzlformat`, `rules_updatesrc`, and `bazel_shlib` to `bazel-starlib`

- .bazelrc
- BUILD.bazel
- bazel_integration_test/private/bazel_integration_test.bzl
- doc/rules_and_macros_overview.md
- tests/params_tests/BUILD.bazel
- tests/params_tests/env_inherit_attr_test.bzl
- tests/params_tests/env_inherit_attr_test.sh
- tests/params_tests/workspace/BUILD.bazel
- tests/params_tests/workspace/WORKSPACE
- tests/params_tests/workspace/noop_test.sh
- Added `env_inherit` to `bazel_integration_test` and `bazel_integration_tests` to allow the `env_inherit` values to be overridden.
- Added `additional_env_inherit` to `bazel_integration_test` and `bazel_integration_tests` to allow additional `env_inherit` values to be specified.
> Allow `env_inherit` values to be added or overridden.

- BUILD.bazel
- README.md
- WORKSPACE
- bazel_integration_test/private/bazel_integration_test.bzl
- bazel_integration_test/private/default_test_runner.bzl
- examples/BUILD.bazel
- examples/custom_test_runner/.bazelrc
- examples/custom_test_runner/BUILD.bazel
- examples/custom_test_runner/WORKSPACE
- examples/custom_test_runner/integration_tests/BUILD.bazel
- examples/use_create_scratch_dir_test.sh
- release/workspace_snippet.tmpl
- tests/tools_tests/create_scratch_dir_test.sh
- tests/tools_tests/find_child_workspace_packages_test.sh
- tests/tools_tests/update_deleted_packages_test.sh
- tools/update_deleted_packages.sh
> Renamed the workspace to `bazel_contrib_rules_bazel_integration_test`.

- BUILD.bazel
- README.md
- WORKSPACE
- bazel_integration_test/private/bazel_integration_test.bzl
- bazel_integration_test/private/default_test_runner.bzl
- examples/BUILD.bazel
- examples/custom_test_runner/.bazelrc
- examples/custom_test_runner/BUILD.bazel
- examples/custom_test_runner/WORKSPACE
- examples/custom_test_runner/integration_tests/BUILD.bazel
- examples/use_create_scratch_dir_test.sh
- release/workspace_snippet.tmpl
- tests/tools_tests/create_scratch_dir_test.sh
- tests/tools_tests/find_child_workspace_packages_test.sh
- tests/tools_tests/update_deleted_packages_test.sh
- tools/update_deleted_packages.sh
> Removed `bazel_` prefix from the workspace name.

- README.md
- doc/custom_test_runners.md
Closes #11.
- Moved custom test runner documentation to its own file.
- Fixed broken syntax and out-of-date doc in `README.md`.
- Added documentation on creating a custom test runner that needs to modify source files.
> Update documentation for custom test runners.

- release/BUILD.bazel
We switch to a custom workspace name, `contrib_rules_bazel_integration_test`, in #51. This specifies the custom name for workspace snippet generation.
> Add custom workspace name to generated workspace snippet.

- bazel_integration_test/deps.bzl
- shared.bazelrc
Related to cgrindel/bazel-starlib#140.
- Upgrade `bazel-skylib` to 1.2.1
- Upgrade `bazel-starlark` to 0.7.0
- Add `--incompatible_disallow_empty_glob` to `shared.bazelrc`
> Upgrade `bazel-starlib` and `bazel-skylib` to support `--incompatible_disallow_empty_glob` flag

- .bazelrc
- bazel_integration_test/private/bazel_integration_test.bzl
- bazel_integration_test/py/bazel_py_integration_tests.bzl
- doc/rules_and_macros_overview.md
- examples/BUILD.bazel
- tests/params_tests/BUILD.bazel
Following the discussion in #70 this PR adds `env` parameter to `bazel_integration_test` and removes passing `CC=clang` by default
> Add env parameter to bazel_integration_test, remove "CC" passing

- tests/tools_tests/find_child_workspace_packages_test.sh
- tests/tools_tests/update_deleted_packages_test.sh
- tools/find_child_workspace_packages.sh
- tools/update_deleted_packages.sh
- Address Bash errors when executing `find_child_workspace_packages.sh` and `update_deleted_packages.sh` with empty child workspaces.
- Address ShellCheck warnings.
> fix: address issues running `find_child_workspace_packages.sh` with empty child workspaces

- .bazelrc
- tools/update_deleted_packages.sh
Related to #81.
- The `deleted_packages` list for this repo changed because the packages are being sorted. It looks like the sort was not working previously or the list was generated before the sort was added to `find_child_workspace_packages.sh`.
> fix: apply suggestions from GH081 code review and address ShellCheck warnings

- tools/BUILD.bazel
- tools/find_child_workspace_packages.sh
- tools/shared_fns.sh
- Moved `find_workspace_dirs` to a `shared_fns.sh` file. This will be used by a new tool in an upcoming PR.
- Addressed ShellCheck warning suggesting the use of `-print0` with `find`.
- Refactored boolean shortcuts to `if` statements.
- Replaced use of `exit_on_error` with `fail`. The `exit_on_error` function no longer exists.
Related to #82.
> chore: additional cleanup for find_child_workspace_packages

- tests/tools_tests/BUILD.bazel
- tests/tools_tests/remove_child_wksp_bazel_symlinks_test.sh
- tools/BUILD.bazel
- tools/remove_child_wksp_bazel_symlinks.sh
If a Bazel workspace has child workspaces and Bazel builds are run in the child workspaces, Bazel will create symlinks in the child workspace directories. This can lead to infinite symlink expansion errors in the parent workspace.
Delete the Bazel symlinks in the child workspaces. This avoids the infinite symlink expansion and preserves the Bazel build outputs for the child workspaces.
Run `@contrib_rules_bazel_integration_test//tools:remove_child_wksp_bazel_symlinks` from the parent workspace. It looks for the Bazel symlinks in the child workspace while keeping the Bazel symlinks in the parent workspace.
> feat: add `remove_child_wksp_bazel_symlinks` to remove child workspace symlinks

- bazel_integration_test/private/bazel_integration_test.bzl
Trying to fix the CI failure here, in the rules_rust tests: https://buildkite.com/bazel/rules-rust-rustlang/builds/7703#01855631-4f26-4779-bb7c-5e96463f074e
```
(00:46:14) ERROR: C:/b/bk-windows-6dj8/bazel/rules-rust-rustlang/test/integration/clippy/BUILD.bazel:3:34: in select_file rule //test/integration/clippy:test_bazel_binary:
Traceback (most recent call last):
File "C:/b/7h7n2dmc/external/bazel_skylib/rules/select_file.bzl", line 36, column 13, in _impl
fail("Can not find specified file in [%s]" % files_str)
Error in fail: Can not find specified file in [external/build_bazel_bazel_6_0_0/bazel.exe]
```
Refs https://github.com/bazelbuild/rules_rust/pull/1731.
Fixes #69.
> Windows support

- bazel_integration_test/private/bazel_binaries.bzl
- tests/BUILD.bazel
- tests/integration_test_impl_tests.bzl
Closes #108
Handles trailing lines in the .bazelversion parser.
Adds unit tests for the parsing function.
I was debating whether to add an integration test for this. However, it seemed much easier to mock the `repository_ctx` object and write a unit test. But, that required exposing the function (dropping the `_` prefix). It's still part of a `private` module, so not part of the public API. But, let me know if you'd prefer some other route.
> Support trailing lines in .bazelversion

- .github/workflows/create_release.yml
- bazel_integration_test/deps.bzl
- release/BUILD.bazel
- Upgrade `bazel-starlib` to 0.12.1.
- Upgrade `gha_create_release` to v2.
- Build a release source archive from the files used to execute the child workspaces. This provides the minimum set of files needed to use the `rules_bazel_integration_test` repository.
Closes #111.
> chore: build a release source archive

- release/BUILD.bazel
> fix: pass the SHA256 for the release archive to the workspace snippet declaration

- BUILD.bazel
- README.md
- WORKSPACE
- bazel_integration_test/private/bazel_integration_test.bzl
- bazel_integration_test/private/default_test_runner.bzl
- doc/custom_test_runners.md
- examples/BUILD.bazel
- examples/custom_test_runner/.bazelrc
- examples/custom_test_runner/BUILD.bazel
- examples/custom_test_runner/WORKSPACE
- examples/custom_test_runner/integration_tests/BUILD.bazel
- examples/use_create_scratch_dir_test.sh
- release/BUILD.bazel
- release/workspace_snippet.tmpl
- tests/tools_tests/create_scratch_dir_test.sh
- tests/tools_tests/find_child_workspace_packages_test.sh
- tests/tools_tests/remove_child_wksp_bazel_symlinks_test.sh
- tests/tools_tests/update_deleted_packages_test.sh
- tools/find_child_workspace_packages.sh
- tools/remove_child_wksp_bazel_symlinks.sh
- tools/update_deleted_packages.sh
- Rename `contrib_rules_bazel_integration_test` to `rules_bazel_integration_test`.
Related to #120.
> chore: change the default name for the repository

- WORKSPACE
- bazel_integration_test/bzlmod/BUILD.bazel
- bazel_integration_test/bzlmod/bazel_binaries.bzl
- bazel_integration_test/bzlmod/bazel_binary_utils.bzl
- bazel_integration_test/bzlmod/workspace_bazel_binaries.bzl
- bazel_integration_test/private/integration_test_utils.bzl
- bazel_integration_test/private/no_deps_utils.bzl
- doc/rules_and_macros_overview.md
- examples/BUILD.bazel
- release/BUILD.bazel
- tests/params_tests/BUILD.bazel
- tests/py_tests/BUILD.bazel
Clients that are using bzlmod now only need to specify the Bazel versions in their `MODULE.bazel`. The `bazel_versions.bzl` is no longer necessary.
- Update `bazel_binaries` to provide the version information.
- Update `workspace_bazel_binaries` to consume the version info so that it can also provide it.
Closes #125.
> feat: expose version values via `bazel_binaries.versions`

- tools/shared_fns.sh
These directories aren't considered by bazel in the first place, so can't be used as test workspaces, and are potentially lots of extra noise in a --deleted_packages value.
> update_deleted_packages: filter out bazelignored directories

- tests/tools_tests/find_child_workspace_packages_test.sh
- tools/find_child_workspace_packages.sh
- tools/shared_fns.sh
- Refactor `filter_bazelignored_directories()`
- Gracefully handle if `.bazelignore` does not exist.
- Do not attempt to ignore if the `path` is the workspace root.
- Address some ShellCheck warnings.
- Add test to ensure that `.bazelignore` directories are respected.
> fix: ensure that bazelignore filter handles missing `.bazelignore`

- bazel_integration_test/private/bazel_binaries.bzl
Currently, if you do not specify `current` and use a bazelversion file, tests run correctly. If you do not specify `current` and use a list of versions, an error occurs.
> Use a default for current version when none is specified.

- bazel_integration_test/py/test_base.py
Windows runfile support is sufficiently different that it will need a different mechanism.
Part of #182.
> Export runfiles environment for non-Windows tests.

- README.md
- bazel_integration_test/bzlmod/bazel_binaries.bzl
- bazel_integration_test/private/bazel_binaries.bzl
- bazel_integration_test/private/bazel_binaries_script.template
- bazel_integration_test/private/bazel_integration_test.bzl
> Use bazelisk to download bazels for tests, instead of trying to download

- bazel_integration_test/private/bazel_binaries.bzl
- Refactor the checks to helper functions.
- Reliably identify arm and amd64 arches.
Closes #194.
> fix: update the OS and arch check for Bazel binary download

- bazel_integration_test/private/bazel_integration_test.bzl
Recreated changes originally in #72 after I messed up the rebase.
Related to #72.
Related to https://github.com/tweag/rules_haskell/pull/1797.
cc: @k1nkreet
> fix: make workspace_file filegroup `testonly`

- MODULE.bazel
- MODULE.bazel.lock
- bazel_integration_test/bzlmod/bazel_binaries.bzl
- examples/custom_test_runner/MODULE.bazel
- Update `bazel_binaries` extension to return metadata listing the declared repositories.
- Update `custom_test_runner` test to properly declare its repositories.
Closes #235.
> feat: return bzlmod extension metadata for declared repositories

- MODULE.bazel
- MODULE.bazel.lock
- bazel_integration_test/bzlmod/bazel_binaries.bzl
- bazel_integration_test/private/BUILD.bazel
- bazel_integration_test/private/bazel_binaries.bzl
- examples/BUILD.bazel
- examples/local_bazel_binary_test.sh
- tools/BUILD.bazel
- tools/fake_bazel.sh
Allow a client to execute Bazel integration tests using a local Bazel binary.
```python
bazel_binaries = use_extension(
"//:extensions.bzl",
"bazel_binaries",
dev_dependency = True,
)
bazel_binaries.download(version_file = "//:.bazelversion")
bazel_binaries.download(version = "6.4.0")
bazel_binaries.local(path = "/path/to/bazel", name = "foo"). # <=== An absolute or relative path to a Bazel binary.
use_repo(
bazel_binaries,
"bazel_binaries",
"build_bazel_bazel_foo",   # <=== The repository name for the local Bazel binary.
)
```
Then, you can use the Bazel binary in integration tests by using the `name` value as the `version`.
```python
script_test(
name = "local_bazel_binary_test",
srcs = ["local_bazel_binary_test.sh"],
bazel_binaries = bazel_binaries,
bazel_version = "foo",  # <=== The …
```
> feat: support local Bazel binaries using `bazel_binaries.local()`

- .gitignore
I accidentally pushed [a commit](https://github.com/bazel-contrib/rules_bazel_integration_test/commit/ac76fcf525b778f4ad808b4bc3594b55fcb2d35a) to `main` that upgrades Bazel to 7.0.0rc3. I created this PR to run CI to ensure that all is well.
> chore: test after accidental push to `main` upgrading Bazel

- tools/find_child_workspace_packages.sh
We respect the bazelignore directories when looking for child workspaces. This adds the same logic when looking for Bazel packages.
Related to #189.
> fix: respect the bazelignore directories when finding Bazel packages

- tests/tools_tests/find_child_workspace_packages_test.sh
- tools/find_child_workspace_packages.sh
- tools/shared_fns.sh
- Added `-r` flag to `xargs` to ensure that the specified command does not run if there are no results in stdin.
- Use `-I {}` with `xargs` to be cross-platform compatible. This ensures that the command will execute for each result.
- Add `-S 511` to `xargs` to ensure that `xargs` does not fail with `xargs: command line cannot be assembled, too long` if the paths are very long. The default command length for `xargs` is 255. 
- Beefed up the unit tests for `find_child_workspace_packages`.
Closes #189.
> fix: do not fail if no results using GNU `xargs`

- MODULE.bazel
- MODULE.bazel.lock
- shared.bazelrc
- tests/tools_tests/remove_child_wksp_bazel_symlinks_test.sh
- tests/tools_tests/setup_test_workspace.sh
There are four issues when running on windows:
1. https://github.com/bazel-contrib/rules_bazel_integration_test/issues/330
2. https://github.com/bazel-contrib/rules_bazel_integration_test/issues/331
3. https://github.com/bazel-contrib/rules_bazel_integration_test/issues/332
4. https://github.com/bazel-contrib/rules_bazel_integration_test/issues/333
This PR fixes 3 and 4.
There are related PRs in bazel-skylib and bazel-starlib. There is no dependency -- the PRs can close in any order.
- https://github.com/cgrindel/bazel-starlib/pull/446 (fixes 1)
- https://github.com/bazelbuild/bazel-skylib/pull/527 (fixes 2)
Before:
--enable_runfiles: 0 pass
--noenable_runfiles: 0 pass
After this PR:
--enable_runfiles: 52 pass, 19 failures
--noenable_runfiles: 51 pass, 20 failures (17 are doc diff-tests …
> fix: windows functionality and tests

- .bcr/presubmit.yml
BCR requires the Bazel version.
> fix: add Bazel version to BCR presubmit

- .bcr/presubmit.yml
These values need to be the same.
> chore: sync the BCR presubmit Bazel version with .bazelversion

- .github/workflows/ci.yml
Apparently, we were still using `macos-12`, which is now [deprecated](https://github.com/bazel-contrib/rules_bazel_integration_test/actions/runs/11665997473?pr=383).
> fix: upgrade to macos-14 GitHub runner

- .github/workflows/ci.yml
Apparently, Xcode 16 was removed from `macos-14` back in October. I am not sure why it is just failing now.
Related to https://github.com/actions/runner-images/issues/10703.
> fix: upgrade to macos-15 runners to avoid missing Xcode error

- bazel_integration_test/private/bazel_binaries.bzl
Unblocks https://github.com/bazelbuild/rules_android/issues/278.
Closes #397.
> Add rules_shell loads where needed

- examples/BUILD.bazel
- examples/simple/BUILD.bazel
- examples/simple/mockascript/private/.another_hidden_file
- examples/simple/mockascript/private/BUILD.bazel
- examples/use_create_scratch_dir_test.sh
- tools/create_scratch_dir.sh
The initial copy will copy over hidden files in sub-directories. The copy `find` logic for hidden files was looking through the entire tree. We really just want to copy the hidden files in the top-level directory.
Also, adjusted the glob pattern for the "non-hidden" file copy per a shellcheck warning.
> fix: hidden files being copied to the wrong directory

- examples/BUILD.bazel
This fixes the failing test from #410.
> Add explicit `--enable_workspace` so that this test works with Bazel 8

- bazel_integration_test/private/bazel_integration_test.bzl
This minimal change in this PR allows me to use example/child workspaces for integration test without creating empty WORKSPACE files.
Following the `README.md` to implement `rules_bazel_integration_test`, I found that the _child_workspaces_ needed to have stubbed/empty `WORKSPACE` files in them; creating empty files caused the error to disappear:
```
$TEST_TMPDIR defined: output root default is '/tmp/bazel' and max_idle_secs default is '15'.
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Analyzing: 104 targets (12 packages loaded, 0 targets configured)
Analyzing: 104 targets (12 packages loaded, 0 targets configured)
ERROR: /home/runner/work/rules_synology/rules_synology/examples/BUILD.bazel:29:24: in select_workspace_file rule …
```
> fix: look for MODULE.bazel in child repos to remove need for stub WORKSPACE

- bazel_integration_test/bzlmod/bazel_binaries.bzl
Addresses wrong arch being used for Java in rules_swift_package_manager integration tests.
> fix: upgrade Bazelisk version to 1.25.0

- .github/workflows/ci.yml
Executing `tidy` on the GitHub MacOS runner started generating different results from the Ubuntu runner and local runs, even when run on MacOS. Until we figure it out, we will disable the tidy check on the MacOS runner.
Related to https://github.com/cgrindel/rules_swift_package_manager/issues/1569.
> fix: disable tidy on macos runner

- README.md
Otherwise the bazel_integration_test target will fail to build with a message like so:
```
ERROR: Skipping '@build_bazel_bazel_7_6_1': No repository visible as '@build_bazel_bazel_7_6_1' from main repository
```
> Add missing bazel_binaries attr in README

- MODULE.bazel
Do not register a python toolchain: this is unnecessary since rules_python registers a default toolchain already. Moreover, this toolchain registration could negatively affect a user of `rules_bazel_integration_test` by registering a toolchain the root module may not want to use (and that might be selected depending on that module's dependency ordering).
Fixes #520
> fix: do not register a python toolchain
